
Table users as U {
  id uuid [pk]
  first_name text [not null]
  last_name text [not null]
  email text [not null]
  avatar_url text [not null]
  role user_role [not null]
}

// This may need to be a table
Enum user_role {
  admin
}

// Auths are authorization records
Table auths as A {
  id uuid [pk]
  user_id uuid [ref: > U.id, not null]
  provider text [not null]
  provider_id text [not null, note: "provider's ID for user"]

  Indexes {
    (user_id, provider) [unique]
    (provider, provider_id) [unique]
  }
}

Table tokens as T {
  id uuid [pk]
  auth_id uuid [ref: > A.id, not null]
  hash text [not null]
  last_login_at timestamp [not null]
  expires_at timestamp [not null]
}

// Form Tools (service provider)
Table form_tools as FT {
  id uuid [pk]
  name text [not null]
  auth_token text
}

Table forms as F {
  id uuid [pk]
  name text [not null]
  form_tool_id uuid [ref: > FT.id]
}

Table form_fields as FF {
  id uuid [pk]
  label text [not null]
  form_id uuid [ref: > F.id]
}

Table form_records as FR {
  id uuid [pk]
  created_by_id uuid [ref: > U.id]
  last_edited_by_id uuid [ref: > U.id]
  form_id uuid [ref: > F.id]
  form_tool_record_id text [not null]
}

Table form_record_field {
  id uuid [pk]
  form_record_id uuid [ref: > FR.id]
  form_field_id uuid [ref: > FF.id]
  value text [not null]
}
