name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: cp test.env .env && touch proxy.env

      - name: Test
        run: make test
